service: my-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.11.4

functions:
  index:
    handler: handler.index
    events:
      -http:
          method: GET
          path: /hello